In [1]:
import numpy as np

In [2]:
# Creating a NumPy Arrays
heights_cm = np.array([153, 130, 165, 176, 100])
print("Heights:", heights_cm)

Heights: [153 130 165 176 100]


In [3]:
# Array Operations
average_height = np.mean(heights_cm)
max_height = np.max(heights_cm)
print("Average Height is: ", average_height)
print("Maximum Height is: ", max_height)

Average Height is:  144.8
Maximum Height is:  176


In [6]:
# Multi Dimentional Array
temperature_data = np.array([[25, 28, 35], [22, 23, 30], [21, 19, 17]])
print(temperature_data)

[[25 28 35]
 [22 23 30]
 [21 19 17]]


In [7]:
# Conversion of celcius into fahrenheit
temp_fahrenheit = (temperature_data* 9 / 5) + 32
print(temp_fahrenheit)

[[77.  82.4 95. ]
 [71.6 73.4 86. ]
 [69.8 66.2 62.6]]


In [11]:
# Zeros and ones 
print("np.zeros:", np.zeros(3))
print("np.zeros:3x3\n", np.zeros((3,3)))

np.zeros: [0. 0. 0.]
np.zeros:3x3
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# Zeros and ones 
print("np.zeros:", np.ones(3))
print("np.zeros:3x3\n", np.ones((3,3)))

np.zeros: [1. 1. 1.]
np.zeros:3x3
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# eye
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# Array attributes and methods 
arr = np.arange(25)
print(arr)
print(arr.reshape(5,5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [18]:
np_array1 = np.array([1, 2, 3])
np_array2 = np.array([4, 5, 6])

# Perform arthmetic operations
print("Addition: ", np_array1 + np_array2)


Addition:  [5 7 9]


In [25]:
# Addition 
addition_result = np.add(np_array1, np_array2)
print(addition_result)

# Subtraction
sub_result = np.subtract(np_array1, np_array2)
print(sub_result)

# Multiplication
multi_result = np.multiply(np_array1, np_array2)
print(multi_result)

# Divide 
divide_result = np.divide(np_array1, np_array2)
print(divide_result)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [26]:
angles = np.array([0, np.pi/4, np.pi/2, 3*np.pi/4, np.pi])
print("Angles:", angles)

Angles: [0.         0.78539816 1.57079633 2.35619449 3.14159265]


In [29]:
# Sine
sine_values = np.sin(angles)
print(sine_values)

# Cosine
cos_values = np.cos(angles)
print(cos_values)

# Tangent
tan_values = np.tan(angles)
print(tan_values)

[0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]
[ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00]
[ 0.00000000e+00  1.00000000e+00  1.63312394e+16 -1.00000000e+00
 -1.22464680e-16]
